# Generated by Django 3.1.5 on 2021-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20210113_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('sexo', models.BooleanField()),
                ('fecha', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=150)),
            ],
        ),
    ]
