# Generated by Django 3.1.5 on 2021-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='sexo',
            field=models.CharField(max_length=150),
        ),
    ]
